OpenGL glwrap: addded functionality, similar to defines, for adding extensions (#extension foo : enable) to the ShaderObject class. The extensions are added _before_ the output locations are defined. This prevents compile-time errors "error C7621: #extension directive must occur before any non-preprocessor token" for fragment and vertex shaders (geometry shaders have no default location bindings).